### ISSUE TITLE
On analytics page split out orgs with approved content vs those without

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#343]
Makes little tricky at the moment to see how many orgs we actually have content from

**Comment by adendarian** [comment]
Could be sensitive - only Admins have access or is this published or do we want to publish to incentivize contributions?  There are enhancements we could consider that facilitate collaboration - but this is not the venue to discuss.

**Comment by alexlittle** [comment]
Currently only Admins have access to this.

For publicizing the contributions, we already have the page with the 
content partners (http://health-orb.org/partners/) - so I think this is 
sufficient right now for publishing the contributions?



On 07/01/16 23:44, adendarian wrote:
>
> Could be sensitive - only Admins have access or is this published or 
> do we want to publish to incentivize contributions? There are 
> enhancements we could consider that facilitate collaboration - but 
> this is not the venue to discuss.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mPowering/django-orb/issues/343#issuecomment-169815121>.
>

-- 
Alex Little
alex@alexlittle.net
http://alexlittle.net
mobile (UK): +44 7548 236 650
skype: alexlittleou
twitter: @alexlittle <https://twitter.com/alexlittle>
