### ISSUE TITLE
Unicode error on adding url to a resource

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#346]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 74: ordinal not in range(128)

So far I've been unable to replicate, am awaiting further info from the user who was getting this error

**Comment by adendarian** [comment]
Take a look at:
http://stackoverflow.com/questions/13512443/python-2-7-unicodedecodeerror-ascii-codec-cant-decode-byte
