### ISSUE TITLE
Tag API is only returning tags that are already attached to a resource

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#380]
When submitting resource updates via the API, the new tags aren't getting returned when requested as they're not attached to a resource (the API process creates the tag first and then adds to the resource).

for example: http://health-orb.org/api/v1/tag/?name=VSO&format=json&username=xxxxx&api_key=xxxxxx returns nothing, although 'vso' is already listed as a tag.

As it;s not returned as a current tag by the API, the upload process then tries to recreate the tag and an error is thrown since it already exists.

Unclear to me exactly why it's not being returned - possible (though I'm not 100% sure) that it's only returning tags if the are attached to an already approved resource.

**Comment by bennylope** [comment]
In Pivotal Tracker: https://www.pivotaltracker.com/story/show/129453963
