### ISSUE TITLE
Update location of language selection in header for mobile

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#438]
It works, but doesn't look great:

![screenshot_20170102-160720](https://cloud.githubusercontent.com/assets/344917/21600884/a7c4e59a-d18b-11e6-8063-f670433009ff.png)

**Comment by bennylope** [comment]
I've been experimenting with some variations here. For now I've cleaned up the navigation itself and removed the "Language" header. Looking at some options to move the language selection out of this area for mobile, at least.
