### ISSUE TITLE
Strategy for db translation updates

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#449]
Need to check that when the export happens, the strings get exported in reliable order (may already be the case?) - so then easier to do a diff and check:
1) for new strings
2) where the English string may have been updated

**Comment by bennylope** [comment]
Is the order of content consistent so that this is repeatable?

**Comment by bennylope** [comment]
The updated appended to PR #453 enforces a consistent ordering. This should be consistent for any given set of models and fields.
