### ISSUE TITLE
Ability to merge tags

### ISSUE THREAD

**Issue by bennylope** [mPowering/django-orb#456]
An admin user should be able to merge two or more tags.

This would result in all instances of the 'loser' tags being replaced by the 'winner' across all tagged items.

**Comment by bennylope** [comment]
@alexlittle I'm presuming that we don't want to copy over tag properties (unless we do!) but what do you want to do about tag tracker? On the one hand, this is presumably access to the same underlying concept, on the other, it's actually accessing a different tag.

**Comment by alexlittle** [comment]
hi - no I don't think we need to copy over the tag properties (these are basically just used for the licensing info currently anyway). For the tag tracker, I think it would be good to update the tag tracker info too. For the tag tracker I guess is more the 'meaning' that we're looking to record, so if eg someone looks at "Latin America" tag or "Latin American Countries" tag and we then combine into "Latin America", then the info that someone has looked for (something like) latin america, means we'd want to preserve that information, whatever the exact tag was.
The other reason for this merge I think will be for typos in the tags, so presumably there won;t be many trackers of the misspelled one - and is same case as above.
