### ISSUE TITLE
Add option to archive a resource

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#462]
Suggest adding an 'archived' option to the status

**Comment by bennylope** [comment]
What does it mean to archive a resource? Is it no longer editable via the non-admin interface? Is it no longer displayed on the web site or via the API?

**Comment by alexlittle** [comment]
Essentially it would be the same as the 'rejected' status. So would no longer be available via the normal user interface, nor the API - but it would still be visible in the django admin pages.
The use case for this is:
Resources that we've had up on the site, but now the medical info has been superceded, so we shouldn't be making publicly available anymore - or other reason (eg publisher requests we remove it)

Currently we've using the rejected status - but this doesn;t really have the same meaning (although functionly it's the same - but no email needs to be send when a resource is archived)
