### ISSUE TITLE
Can't drag resources into a course

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#493]
Unclear why this is - no error in JS console. Happening on Firefox 54/Ubuntu 16.04

**Comment by courcelan** [comment]
Bootstrap puts icons on psuedo-elements and it looks as though 1) firefox does not allow buttons to be draggable (handles) and 2) Firefox doesn't allow pseudo-elements to be draggable (handles). We're reworked this handle so that you can drag in Firefox
