### ISSUE TITLE
Request extra info on resource download/link

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#509]
Given that a user will already be logged in to access the files/links for a resource (#508), before being able to access the download/link, they should be asked the following (either as pop up or as new page):

"Please let us know how you are intending to use this resource:" With a drop down list, consisting of the following options:

- "For my own learning"
- "I'm just browsing"
- "For training frontline health workers"
- "Other"

If a user selects "For my own learning" or "I'm just browsing", once they submit the form they go straight to the download/link

If a user selects "For training frontline health workers" they should then be asked (as 'auto appearing' additional questions on the same page):

- "How many frontline health workers are you intending to train?" - can only enter a non-zero positive integer
- "What type/cadre of frontline health workers are you intending to train?" - options from a drop down list of the 'audiences' (that resources can be tagged with)

If a user selects "Other", they should be asked (as 'auto appearing' additional question on the same page)

- "Please explain" - with a free-text field (they must enter something)

Would suggest that this extra data can be stored as additional fields on the ResourceTracker model

**Comment by alexlittle** [comment]
Couple of minor updates for this: 

- On the download survey page, if the user selects 'for training frontline health workers', the follow up questions (numbers & cadre) should be required - doesn't seem to be at the moment
- For the cadre/type drop down, I think it may be best to have a '--' type option at the top that is pre-selected (on their first download at least - subsequent downloads will have the cadre pre-selected), so user do then need to actively select the applicable cadre - otherwise they may end up just leaving the default selected

**Comment by bennylope** [comment]
Updated via #520.
