### ISSUE TITLE
After login/registration user should go back to the resource

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#513]
When clicking on login/register link on resource metadata page, the user ends up back at the homepage. Would be much better if they could return to the same resource metadata page (using hidden 'next' field on these forms?)

**Comment by bennylope** [comment]
So this is ready or just about for a PR (I'll issue one anyhow) but when reviewing I noticed there are a few minor changes required for #507 yet. 

That made a few fields no longer required, and the current validation still requires them. No big deal, except that these are non-nulllable fields and the `ProfileForm` still requires them.

So I want to verify here that we're going to make these fields optional for users in general, not just in the registration form.
