### ISSUE TITLE
Survey info- cadre and numbers being added when learning/browsing

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#523]
If I enter info for a cadre and numbers of health workers when accessing one resource, then I go to another resource, but select either learning/browsing/other, then the cadre and number info is still being added to these records.
For now it's ok as can filter these out when creating a report, but would be good if these fields were automatically blanked out if another reason is chosen.

**Comment by bennylope** [comment]
#524 fixes this.

The data is just always saved to the session, so it's simplest here to filter this out when validating the form.
